<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Articles
 * @property Doctrine_Collection $ArticleTag
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method Doctrine_Collection getArticles()   Returns the current record's "Articles" collection
 * @method Doctrine_Collection getArticleTag() Returns the current record's "ArticleTag" collection
 * @method Tag                 setName()       Sets the current record's "name" value
 * @method Tag                 setArticles()   Sets the current record's "Articles" collection
 * @method Tag                 setArticleTag() Sets the current record's "ArticleTag" collection
 * 
 * @package    sis
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tag');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Article as Articles', array(
             'refClass' => 'ArticleTag',
             'local' => 'tag_id',
             'foreign' => 'article_id'));

        $this->hasMany('ArticleTag', array(
             'local' => 'id',
             'foreign' => 'tag_id'));
    }
}