<?php

/**
 * ArticleTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticleTag');
    }
}