<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/03/19 11:12:07

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=symfony',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
